config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'homes/top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :customers, only: [:index, :edit, :update, :show, :update] do
      get 'orders' => 'orders#index'
    end
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    get "search" => "searches#search"
  end
  namespace :public do
    get 'homes/top'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  scope module: :public do
    get 'customers/my_page' => 'customers#show'
    get 'customers/infomation/edit' => 'customers#edit'
    patch '/customers/infomation' => 'customers#update'
    # 顧客の退会確認画面
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    # 退会処理用のルーティング
    patch 'customers/withdrawal' => 'customers#withdrawal'
    resources :items, only: [:index, :show]
    get 'orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :index, :show, :create]
    post 'orders/confirm' => 'orders#confirm'
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete "clear"
      end
    end
    get "search" => "searches#search"
    resources :genres, only: [:show]
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about', as: 'about'
  get 'admin' => 'admin/homes#top', as: 'admin'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre, optional: true
  has_many :orders, through: :order_details

  has_one_attached :image

  validates :name, presence: true
  validates :caption, presence: true
  validates :genre, presence: true
  validates :price, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.png")
      image.attach(io: File.open(file_path), filename: "no_image.png", content_type: "image/png")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
    tax = 1.1
    (self.price * tax).to_i
  end
  
  def self.looks(search, word)
    @item = Item.where("name LIKE?", "%#{word}%")
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_select_genres

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品情報を登録しました。"
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品情報を変更しました。"
    else
      render 'new'
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :caption, :price, :is_sales, :image)
  end

  def set_select_genres
    @genres = Genre.all.map {|genre| [genre.name, genre.id] }.unshift(["--選択してください--", nil])
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<%= form_with model: [:admin, item] do |f| %>
  <div class="form-group row mt-5">
    <%= f.label :image, "商品画像", class: "col-4 col-form-label" %>
    <%= f.file_field :image, class: "btn" %>
  </div>
  <div class="form-group row">
    <%= f.label :name, "商品名", class: "col-4 col-form-label" %>
    <%= f.text_field :name, class: "col-7 form-control", placeholder: "商品名" %>
  </div>
  <div class="form-group row">
    <%= f.label :caption, "商品説明", class: "col-4 col-form-label" %>
    <%= f.text_area :caption, class: "col-7 form-control", placeholder: "ここに説明文を記述します" %>
  </div>
  <div class="form-group row">
    <%= f.label :genre, "ジャンル", class: "col-4 col-form-label" %>
    <%= f.select :genre_id, genres,{},{class: "form-select"} %>
  </div>
  <div class="form-group row">
    <%= f.label :price, "税抜価格", class: "col-4 col-form-label" %>
    <%= f.text_field :price, class: "col-7 form-control", placeholder: "1000" %>円
  </div>
  <div class="form-group row">
    <%= f.label :is_sales, "販売ステータス", class: "col-4 col-form-label" %>
    <div class="col-7 pl-0">
      <%= f.radio_button :is_sales, :true %>
      <%= f.label :is_sales, "販売中", {value: :true, style: "display: inline-block;"} %>&emsp;
      <%= f.radio_button :is_sales, :false %>
      <%= f.label :is_sales, "販売停止中", {value: :false, style: "display: inline-block;"} %>
    </div>
  </div>
  <div class="form-group text-center">
    <% if request.path_info == new_admin_item_path %>
      <%= f.submit "新規登録", class: "btn btn-base px-4 py-2" %>
    <% else %>
      <%= f.submit "変更を保存", class: "btn btn-base px-4 py-2" %>
    <% end %>
  </div>
<% end %>

app/views/admin/items/_item_index.html.erb
<div class="row pb-5">
  <div class="col-md-10">
    <table class="table">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id), class: "text-dark" %></td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_sales == true %>
              <p class="text-success"><strong>販売中</strong></p>
            <% else %>
              <p class="text-secondary"><strong>販売停止中</strong></p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row pb-5">
    <div class="w-75 mx-auto">
      <h4 class="mt-5"><span style="background: #FFEBD2;">商品編集</span></h4>
      <div class="col w-75 mx-auto">
        <%= render 'layouts/errors', obj: @item %>
        <%= render 'form', item: @item, genres: @genres %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row justify-content-between">
    <div class="col-4 mt-5 mb-3">
      <h4><span style="background: #FFEBD2;">商品一覧</span></h4>
    </div>
    <div class="col-4 mt-4 text-right">
      <%= link_to new_admin_item_path do %>
        <%= image_tag 'cake.png', class: "plus-button" %>
      <% end %>
    </div>
  </div>
  <%= render 'item_index', items: @items %>
  <div class="pagination justify-content-center">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container pb-4">
  <div class="row mb-5">
    <div class="w-75 mx-auto">
      <h4 class="mt-5"><span style="background: #FFEBD2;">商品新規登録</span></h4>
      <div class="col w-75 mx-auto">
        <div>
        <%= render 'layouts/errors', obj: @item %>
        </div>
        <%= render 'form', item: @item, genres: @genres %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container pb-4">
  <h4 class="mt-5"><span style="background: #FFEBD2;">商品詳細</span></h4>
  <div class="row mb-5">
    <div class="col-4">
      <%= image_tag @item.get_image(300,300), class: "rounded" %>
    </div>
    <div class="col-8">
      <table class="table mt-4">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.caption %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td>税込価格</br>（税抜価格）</td>
            <td><%= @item.add_tax_price.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <% if @item.is_sales == true %>
                <p class="text-success"><strong>販売中</strong></p>
              <% else %>
                <p class="text-secondary"><strong>販売停止中</strong></p>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= link_to "編集する", edit_admin_item_path, class: "btn btn-base mt-3 ml-5 px-4 py-2" %>
    </div>
  </div>
</div>