config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'homes/top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :customers, only: [:index, :edit, :update, :show, :update] do
      get 'orders' => 'orders#index'
    end
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    get "search" => "searches#search"
  end
  namespace :public do
    get 'homes/top'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  scope module: :public do
    get 'customers/my_page' => 'customers#show'
    get 'customers/infomation/edit' => 'customers#edit'
    patch '/customers/infomation' => 'customers#update'
    # 顧客の退会確認画面
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    # 退会処理用のルーティング
    patch 'customers/withdrawal' => 'customers#withdrawal'
    resources :items, only: [:index, :show]
    get 'orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :index, :show, :create]
    post 'orders/confirm' => 'orders#confirm'
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete "clear"
      end
    end
    get "search" => "searches#search"
    resources :genres, only: [:show]
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about', as: 'about'
  get 'admin' => 'admin/homes#top', as: 'admin'
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 退会してなければtrueを返す
  def active_for_authetication?
    super && (is_active == true)
  end


  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def self.looks(search, word)
    @customer = Customer.where(["first_name LIKE? OR last_name LIKE? OR first_name_kana LIKE? OR last_name_kana LIKE?", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%"])
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 before_action :authenticate_admin!

  # 会員一覧
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  # 会員詳細画面
  def show
    @customer = Customer.find(params[:id])
  end

  # 会員編集画面
  def edit
    @customer = Customer.find(params[:id])
  end

  # 会員情報更新
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path,notice: "会員情報を更新しました。"
    else
      render 'edit'
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :phone_number, :is_active)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_form.html.erb
<%= form_with model: [:admin, customer] do |f| %>
<div class="row mb-4">
  <label class="col-lg-2">名前</label>
  <label class="col-lg-1">(姓)</label>
  <div class="col-lg-3">
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", placeholder: "令和", size: 30 %>
  </div>
  <label class="col-lg-1">(名)</label>
  <div class="col-lg-3">
    <%= f.text_field :first_name,autofocus: true, autocomplete: "first_name",  placeholder: "道子", size: 30 %>
  </div>
</div>

<div class="row mb-4">
  <label class="col-lg-2">フリガナ</label>
  <label class="col-lg-1">(セイ)</label>
  <div class="col-lg-3">
    <%= f.text_field :last_name_kana, autoforcus: true, autocomplete: "last_name_kana",  placeholder: "レイワ", size: 30 %>
  </div>
  <label class="col-lg-1">(メイ)</label>
  <div class="col-lg-3">
    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana",  placeholder: "ミチコ", size: 30 %>
  </div>
</div>

<div class="row mb-4">
  <label class="col-lg-3">メールアドレス</label>
  <div class="col-lg-4">
    <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: 'sample@example.com', size: 30 %>
  </div>
</div>

<div class="row mb-4">
  <label class="col-lg-3">郵便番号(ハイフンなし)</label>
  <div class="col-lg-4">
    <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: '0000000', size: 30 %>
  </div>
</div>

<div class="row mb-4">
  <label class="col-lg-3">住所</label>
  <div class="col-lg-4">
    <%= f.text_field :address, autofocus: true, autocomplete: "address", placeholder: '東京都渋谷区代々木神圓街０−０', size: 85 %>
  </div>
</div>

<div class="row mb-4">
  <label class="col-lg-3">電話番号(ハイフンなし)</label>
  <div class="col-lg-4">
    <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", placeholder: '0000000000', size: 30 %>
  </div>
</div>

<div class="row mb-4">
  <label class="col-lg-3">会員ステータス</label>
  <div class="col-lg-4">
    <%= f.radio_button :is_active, :true %>
    <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>&emsp;
    <%= f.radio_button :is_active, :false %>
    <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block;"} %>
  </div>
</div>

<div class="row mb-4">
  <div class="col-lg-3"></div>
  <div class="col-lg-4">
    <%= f.submit "変更を保存", class: 'btn btn-base w-75' %>
  </div>
</div>
<% end %>

app/views/admin/customers/edit.html.erb
<div class="container mt-4 pb-4">
  <h4 class="px-4 mb-4"><span style="background: #FFEBD2;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span></h4>

  <div class="row mb-4 ">
    <label class="col-lg-3">会員ID</label>
    <div class="col-lg-4">
      <%= @customer.id %>
    </div>
  </div>
  <%= render 'form', customer: @customer %>
</div>

app/views/admin/customers/index.html.erb
<div class="container mt-4 pb-4">
  <div class="col-md-12">
    <h4 class="mb-5 ml-5"><span style="background: #FFEBD2;">会員一覧</span></h4>

    <table class="table col-md-10 text-center">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td>
            <%= customer.id %>
          </td>
          <td>
            <%= link_to admin_customer_path(customer) do %>
            <%= customer.last_name %><%= customer.first_name %>
            <% end %>
          </td>
          <td>
            <%= customer.email %>
          </td>
          <td>
            <% if customer.is_active == true %>
              <p class="text-success">有効</p>
            <% else %>
              <p class="">退会</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination justify-content-center">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container mt-4 pb-4">
  <div class="col-md-12">
    <h4 class="px-4 mb-4"><span style="background: #FFEBD2;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span></h4>
    <table class="table table-borderless">
      <tr>
        <td class="col-md-2">会員ID</td>
        <td class="col-md-5"><%= @customer.id %></td>
      </tr>
      <tr>
        <td class="col-md-2">氏名</td>
        <td class="col-md-5"><%= @customer.last_name %>&emsp;<%= @customer.first_name %></td>
      </tr>
      <tr>
        <td class="col-md-2>">フリガナ</td>
        <td class="col-md-5"><%= @customer.last_name_kana %>&emsp;<%= @customer.first_name_kana %></td>
      </tr>
       <tr>
        <td class="col-md-2>">郵便番号</td>
        <td class="col-md-5"><%= @customer.postal_code %></td>
      </tr>
       <tr>
        <td class="col-md-2>">住所</td>
        <td class="col-md-5"><%= @customer.address %></td>
      </tr>
       <tr>
        <td class="col-md-2>">電話番号</td>
        <td class="col-md-5"><%= @customer.phone_number %></td>
      </tr>
       <tr>
        <td class="col-md-2>">メールアドレス</td>
        <td class="col-md-5"><%= @customer.email %></td>
      </tr>
       <tr>
        <td class="col-md-2>">会員ステータス</td>
        <td class="col-md-5">
          <% if @customer.is_active == true %>
            <p class="text-success">有効</p>
          <% else %>
            <p class="">退会</p>
          <% end %></td>
      </tr>
      <tr>
        <td></td>
        <td class="col-md-5">
          <%= link_to "編集する", edit_admin_customer_path(@customer), class: 'btn btn-base' %>&emsp;
          <%= link_to "注文履歴一覧を見る", admin_customer_orders_path(@customer), class: 'btn btn-base' %>
        </td>
      </tr>
    </table>
  </div>
</div>