config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'homes/top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :customers, only: [:index, :edit, :update, :show, :update] do
      get 'orders' => 'orders#index'
    end
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    get "search" => "searches#search"
  end
  namespace :public do
    get 'homes/top'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  scope module: :public do
    get 'customers/my_page' => 'customers#show'
    get 'customers/infomation/edit' => 'customers#edit'
    patch '/customers/infomation' => 'customers#update'
    # 顧客の退会確認画面
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    # 退会処理用のルーティング
    patch 'customers/withdrawal' => 'customers#withdrawal'
    resources :items, only: [:index, :show]
    get 'orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :index, :show, :create]
    post 'orders/confirm' => 'orders#confirm'
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete "clear"
      end
    end
    get "search" => "searches#search"
    resources :genres, only: [:show]
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about', as: 'about'
  get 'admin' => 'admin/homes#top', as: 'admin'
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_genre, only: [:edit, :update]
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def find_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_index.html.erb
<table class="border bordered" style="width: 170px;height: 200px;border-collapse: separate;border-radius: 5px;background-color: #478384;">
  <thead class="table table-borderless">
    <tr class="text-center">
      <th style="color:white;">ジャンル検索</th>
    </tr>
  </thead>
  <tbody style="background-color: white;">
    <% @genres.each do |genre| %>
      <tr class="d-flex align-items-start">
        <td class="ml-2 mb-3"><li><%= link_to genre.name, genre_path(genre),  class: "text-dark" %></li></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/genres/edit.html.erb
<div class="container pb-5">
  <h4 class="mt-3 mb-3"><span style="background: #FFEBD2;">ジャンル編集</span></h4>
  <%= render 'layouts/errors', obj: @genre %>
  <%= form_with model: @genre, url: admin_genre_path(@genre) do |f| %>
    <div class="row">
      <label class="col-md-2">ジャンル名</label>
      <div class="col-md-3">
        <%=f.text_field :name, class: 'form-control', placeholder: 'ジャンル名' %>
      </div>
      <div class="col-md-4">
        <%= f.submit '編集', class: 'btn btn-base' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container pb-4">
  <h4 class="mt-3 mb-3"><span style="background: #FFEBD2;">ジャンル一覧・追加</span></h4>
  <%= render 'layouts/errors', obj: @genre %>
  <%= form_with model: @genre, url: admin_genres_path do |f| %>
    <div class="my-4 form-group row">
      <%= f.label :name, "ジャンル名", class: "col-3 col-form-label text-center" %>
      <%=f.text_field :name, class: 'form-control', class: "col-3 form-control", placeholder: "ジャンル名" %>
      <div class="ml-3">
        <%= f.submit '新規登録', class: 'btn btn-base' %>
      </div>
    </div>
  <% end %>
  <div class="col-md-3 mt-5">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>ジャンル</th>
          <th></th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to '編集', edit_admin_genre_path(genre), class: 'btn btn-base' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>