config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'homes/top'
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :customers, only: [:index, :edit, :update, :show, :update] do
      get 'orders' => 'orders#index'
    end
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    get "search" => "searches#search"
  end
  namespace :public do
    get 'homes/top'
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  scope module: :public do
    get 'customers/my_page' => 'customers#show'
    get 'customers/infomation/edit' => 'customers#edit'
    patch '/customers/infomation' => 'customers#update'
    # 顧客の退会確認画面
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    # 退会処理用のルーティング
    patch 'customers/withdrawal' => 'customers#withdrawal'
    resources :items, only: [:index, :show]
    get 'orders/complete' => 'orders#complete'
    resources :orders, only:[:new, :index, :show, :create]
    post 'orders/confirm' => 'orders#confirm'
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete "clear"
      end
    end
    get "search" => "searches#search"
    resources :genres, only: [:show]
  end

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about', as: 'about'
  get 'admin' => 'admin/homes#top', as: 'admin'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  validates :quantity, presence: true

  def subtotal
    self.item.add_tax_price.to_i * self.quantity.to_i
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 退会してなければtrueを返す
  def active_for_authetication?
    super && (is_active == true)
  end


  has_many :cart_items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def self.looks(search, word)
    @customer = Customer.where(["first_name LIKE? OR last_name LIKE? OR first_name_kana LIKE? OR last_name_kana LIKE?", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%"])
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre, optional: true
  has_many :orders, through: :order_details

  has_one_attached :image

  validates :name, presence: true
  validates :caption, presence: true
  validates :genre, presence: true
  validates :price, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.png")
      image.attach(io: File.open(file_path), filename: "no_image.png", content_type: "image/png")
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def add_tax_price
    tax = 1.1
    (self.price * tax).to_i
  end
  
  def self.looks(search, word)
    @item = Item.where("name LIKE?", "%#{word}%")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum status: {payment_waiting: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, sent: 4}
  enum payment: {credit_card: 0, transfer: 1}

  def total
    order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal }
  end

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def const_shipping_cost
    self.shipping_cost = 800
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum product_status: {impossible: 0, waiting: 1, production: 2, completion: 3}
  
  def add_tax_price
    tax = 1.1
    (self.item.price * tax).to_i
  end
  
  def subtotal
    self.item.add_tax_price.to_i * self.quantity.to_i
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def order_address
    '〒' + self.postal_code + ' ' + self.address + ' ' + self.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_path
      else
        root_path
      end 
    end
    
    def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :admin
        new_admin_session_path
      elsif resource_or_scope == :customer
        root_path
      else 
        root_path
      end 
    end 
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :phone_number, :encrypted_password, :password_confirmation])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
   :customer
  end

  def resource
   @resource ||= Customer.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:customer]
  end
end

app/helpers/hoems_helper.rb
module HoemsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="d-flex align-items-center justify-content-center" style="height: 110px;">
    <p style="font-size: 16px;">©NaganoCake. All Rights Reserved.</p>
    <ul class="sns ml-5">
      <i class="fab fa-twitter-square mr-1"></i>
      <i class="fab fa-twitch mr-1"></i>
      <i class="fab fa-youtube"></i>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background: #FFEBD2;">
    <div class="container">
      <a class="navbar-brand" href="/"><span><%= image_tag 'logo.jpg', :size => '200x100' %></span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li>
              <%= link_to admin_items_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Products</strong><small style= color:#0b0b33;>商品一覧</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Customers</strong><small style= color:#0b0b33;>会員一覧</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_homes_top_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Orders</strong><small style= color:#0b0b33;>注文履歴一覧</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to admin_genres_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Genres</strong><small style= color:#0b0b33;>ジャンル一覧</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Log out</strong><small style= color:#0b0b33;>ログアウト</small></span>
              <% end %>
            </li>
          <% elsif customer_signed_in? %>
            <p>ようこそ、<%= current_customer.last_name %>さん！</p>
            <li>
              <%= link_to customers_my_page_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>MyPage</strong><small style= color:#0b0b33;>マイページ</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to items_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Products</strong><small style= color:#0b0b33;>商品一覧</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to cart_items_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Cart</strong><small style= color:#0b0b33;>カート</small></span>
              <% end %>
            </li>
            <li>
               <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                 <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Log out</strong><small style= color:#0b0b33;>ログアウト</small></span>
               <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>About</strong><small style= color:#0b0b33;>概要</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to items_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Products</strong><small style= color:#0b0b33;>商品一覧</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Sign in</strong><small style= color:#0b0b33;>新規登録</small></span>
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
                <span class="btn d-flex flex-column"><strong style= color:#0b0b33;>Log in</strong><small style= color:#0b0b33;>ログイン</small></span>
              <% end %>
            </li>
          <% end %>
        </ul>
        <div class="search_form">
          <% if admin_signed_in? %>
            <%= form_with url: admin_search_path, locol: true, method: :get do |f| %>
              <%= f.text_field :word %>
              <%= f.submit "検索", class: "btn-sm" %>
            <% end %>
          <% else %>
            <%= form_with url: search_path, local: true, method: :get do |f| %>
              <%= f.text_field :word %>
              <%= f.submit "検索", class: "btn-sm" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="container pt-4">
        <p id="notice"><%= notice %></p>
      </div>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>